spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unittests
    username: postgres
    password: postgres1!
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
server:
  port: ${PORT:8080}
logging:
  level:
    org.hibernate.SQL: warn

app:
  payment:
    fail-amount: -1
